---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: create route to vault
      kubernetes.core.k8s:
        kind: Namespace
        api_version: v1
        state: absent
        name: "{{ vault_namespace | default('vault-lab') }}"

...
