---
- hosts: localhost
  gather_facts: false
  vars:
    helm_chart_url: "https://helm.releases.hashicorp.com"
    suffix_ns: vault-lab

  tasks:
    - name: add hashicorp helm repo
      kubernetes.core.helm_repository:
        name: hashicorp
        repo_url: "{{ helm_chart_url }}"

    - name: get namspace prefix
      ansible.builtin.shell: oc whoami | cut -f1 -d"@"
      register: prefix_ns

    - name: debug prefix_ns
      ansible.builtin.set_fact:
        vault_ns: "{{ prefix_ns.stdout + '-' + suffix_ns }}"

    - name: deploy latest hashicorp vault
      kubernetes.core.helm:
        name: vault
        release_namespace: "{{ vault_namespace | default(vault_ns) }}"
        create_namespace: true
        state: present
        chart_ref: hashicorp/vault
        values:
          global:
            openshift: true

    - name: create route to vault
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Route
          metadata:
            name: vault-route
            namespace: "{{ vault_namespace | default(vault_ns) }}"
          spec:
            path: /
            to:
              kind: Service
              name: vault
            port:
              targetPort: 8200

...
